# Form implementation generated from reading ui file 'forgotPassword.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_passwordReset(object):
    def setupUi(self, passwordReset):
        passwordReset.setObjectName("passwordReset")
        passwordReset.resize(700, 600)
        passwordReset.setMaximumSize(QtCore.QSize(700, 600))
        passwordReset.setStyleSheet("background: white;")
        self.frame = QtWidgets.QFrame(parent=passwordReset)
        self.frame.setGeometry(QtCore.QRect(40, 200, 621, 371))
        self.frame.setStyleSheet("border: 1px solid grey;\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.emailEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.emailEdit.setGeometry(QtCore.QRect(30, 30, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.emailEdit.setFont(font)
        self.emailEdit.setStyleSheet("border-radius: 0px;\n"
"color: black;")
        self.emailEdit.setReadOnly(True)
        self.emailEdit.setObjectName("emailEdit")
        self.passwordEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.passwordEdit.setGeometry(QtCore.QRect(30, 100, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("border-radius: 0px;\n"
"color: black;")
        self.passwordEdit.setObjectName("passwordEdit")
        self.confirmPasswordEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.confirmPasswordEdit.setGeometry(QtCore.QRect(30, 170, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.confirmPasswordEdit.setFont(font)
        self.confirmPasswordEdit.setStyleSheet("border-radius: 0px;\n"
"color: black;")
        self.confirmPasswordEdit.setObjectName("confirmPasswordEdit")
        self.otpCodeEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.otpCodeEdit.setGeometry(QtCore.QRect(30, 240, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.otpCodeEdit.setFont(font)
        self.otpCodeEdit.setStyleSheet("border-radius: 0px;\n"
"color: black;")
        self.otpCodeEdit.setObjectName("otpCodeEdit")
        self.resetPasswordButton = QtWidgets.QPushButton(parent=self.frame)
        self.resetPasswordButton.setGeometry(QtCore.QRect(30, 310, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(18)
        self.resetPasswordButton.setFont(font)
        self.resetPasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.resetPasswordButton.setStyleSheet("background: #5968B0;\n"
"color: white;\n"
"border: opx;")
        self.resetPasswordButton.setObjectName("resetPasswordButton")
        self.label_2 = QtWidgets.QLabel(parent=passwordReset)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #5968B0;")
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(parent=passwordReset)
        self.graphicsView.setGeometry(QtCore.QRect(260, 10, 181, 131))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(passwordReset)
        QtCore.QMetaObject.connectSlotsByName(passwordReset)

    def retranslateUi(self, passwordReset):
        _translate = QtCore.QCoreApplication.translate
        passwordReset.setWindowTitle(_translate("passwordReset", "Tafa Player Forgot Password"))
        self.emailEdit.setPlaceholderText(_translate("passwordReset", "Email / Phone"))
        self.passwordEdit.setPlaceholderText(_translate("passwordReset", "Password"))
        self.confirmPasswordEdit.setPlaceholderText(_translate("passwordReset", "Confirm Password"))
        self.otpCodeEdit.setPlaceholderText(_translate("passwordReset", "Otp Code"))
        self.resetPasswordButton.setText(_translate("passwordReset", "Reset Password"))
        self.label_2.setText(_translate("passwordReset", "Forgot Password"))
