# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verifyotp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verifyOtpForm(object):
    def setupUi(self, verifyOtpForm):
        verifyOtpForm.setObjectName("verifyOtpForm")
        verifyOtpForm.resize(600, 300)
        verifyOtpForm.setMaximumSize(QtCore.QSize(600, 300))
        self.verticalLayoutWidget = QtWidgets.QWidget(verifyOtpForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setStyleSheet("background: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.otpCodeInput = QtWidgets.QLineEdit(self.frame)
        self.otpCodeInput.setGeometry(QtCore.QRect(60, 140, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.otpCodeInput.setFont(font)
        self.otpCodeInput.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid gray;\n"
"color: black;")
        self.otpCodeInput.setInputMask("")
        self.otpCodeInput.setText("")
        self.otpCodeInput.setObjectName("otpCodeInput")
        self.verifyOtpButton = QtWidgets.QPushButton(self.frame)
        self.verifyOtpButton.setGeometry(QtCore.QRect(50, 240, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.verifyOtpButton.setFont(font)
        self.verifyOtpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verifyOtpButton.setStyleSheet("background: #5968B0;\n"
"color:white;\n"
"border: 0px;\n"
"border-radius:5px;")
        self.verifyOtpButton.setObjectName("verifyOtpButton")
        self.resendOtpButton = QtWidgets.QPushButton(self.frame)
        self.resendOtpButton.setGeometry(QtCore.QRect(370, 140, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(15)
        self.resendOtpButton.setFont(font)
        self.resendOtpButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resendOtpButton.setStyleSheet("background: #5968B0;\n"
"color:white;\n"
"border: 0px;\n"
"border-radius: 5px;")
        self.resendOtpButton.setObjectName("resendOtpButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 30, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #5968B0;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(39, 99, 511, 121))
        self.frame_2.setStyleSheet("border: 1px solid gray;\n"
"border-radius: 10px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.otpCodeInput.raise_()
        self.verifyOtpButton.raise_()
        self.resendOtpButton.raise_()
        self.label.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(verifyOtpForm)
        QtCore.QMetaObject.connectSlotsByName(verifyOtpForm)

    def retranslateUi(self, verifyOtpForm):
        _translate = QtCore.QCoreApplication.translate
        verifyOtpForm.setWindowTitle(_translate("verifyOtpForm", "Tafa Player Verify Otp"))
        self.otpCodeInput.setPlaceholderText(_translate("verifyOtpForm", "OTP CODE"))
        self.verifyOtpButton.setText(_translate("verifyOtpForm", "VERIFY OTP"))
        self.resendOtpButton.setText(_translate("verifyOtpForm", "RESEND OTP"))
        self.label.setText(_translate("verifyOtpForm", "TAFA PLAYER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verifyOtpForm = QtWidgets.QWidget()
    ui = Ui_verifyOtpForm()
    ui.setupUi(verifyOtpForm)
    verifyOtpForm.show()
    sys.exit(app.exec_())
